### ISSUE TITLE
Cannot connect to local instance

### ISSUE THREAD

**Issue by IntelMiner** [shiroyashik/sculptor#1]
Hello! 

Thank you for putting up this alternative Figura back-end.

I ran the following steps but the Figura server doesn't seem to receive any connections

`Create avatar folder`
`Copy config.example.toml to Config.toml`
`cargo build`
`cargo run`

I'm unclear about if a reverse proxy is needed since I'm under Linux. But pointing Figura directly at the internal IP just says "Cloud disconnected"

**Comment by IntelMiner** [comment]
Update: Added Caddy as an SSL proxy. Seems to connect now (yay!)

However upon connecting I get

`Attention! The required UUID for subscription was not found`

**Comment by IntelMiner** [comment]
Update:

Added a Caddy SSL proxy. Seems to work now

However when trying to upload about a 3MB avatar it results in this error

![image (1)](https://github.com/shiroyashik/sculptor/assets/1777604/5397ee02-fde3-4972-8546-2624ddfc8a86)

**Comment by shiroyashik** [comment]
Try increasing the "maxAvatarSize" limit in Config.toml

**Comment by shiroyashik** [comment]
Fixed in [Pre-patch 0.2.1 limitations fixed](https://github.com/shiroyashik/sculptor/commit/83533919f3c3ff40f49d970e0ac696803ab1bcfa) commit
